### ISSUE TITLE
descrambling

### ISSUE THREAD

**Issue by sentest** [neo7530/emmg#1]
after running you ecmg channels are encrypting how would you go about decrypting

**Comment by neo7530** [comment]
You can use a original irdeto 1 smart card, or use my funcard in a irdeto-ci to descramble. Or use oscam with a card reader.

**Comment by sentest** [comment]
do you have to update the entitlements for the card?

**Comment by neo7530** [comment]
Yea, the correct key and channel ID should be activated on card.

**Comment by sentest** [comment]
final question what is the correct commands to start ecmg and emmg. for ecmg i just did ./binary port but cant get emmg started

**Comment by neo7530** [comment]
The emmg starts with "emmg port" too, but first the stream has to be online. Emmg is a TCP client so the server (stream) has to be reachable first.
